---
- name: administrative playbook
  hosts: 
    - lj_ubuntu
  tasks:
    - name: Create simple file
      file:
        path: /tmp/simple.txt
        state: touch
    - name: Print home variable
      shell:
        cmd: echo $HOME
      register: domov
    - debug:
        var: domov

    - name: Print hostname
      shell:
        cmd: hostname
      register: hostik
    - debug:
        var: hostik