---
# handlers file for lamp
- name: start mysql
  become: yes
  service: 
    name: mysql 
    state: started

- name: start apache2
  become: yes
  service: 
    name: apache2 
    state: started

- name: start mariadb
  become: yes
  service: 
    name: mariadb 
    state: started

- name: start httpd
  become: yes
  service: 
    name: httpd 
    state: started